Repository openshift/assisted-installer-agent, pull requests merged in 2021-11, with the labels that each got.

#250 MGMT-7941: Introduce dry mode to the agent
  .dockerignore
  go.mod
  go.sum
  src/agent/main/main.go
  src/apivip_check/main/main.go
  src/commands/service_api.go
  src/commands/step_processor.go
  src/config/dry_run_config.go
  src/config/logs_sender_config.go
  src/connectivity_check/main/main.go
  src/container_image_availability/container_image_availability.go
  src/container_image_availability/container_image_availability_test.go
  src/container_image_availability/main/main.go
  src/dhcp_lease_allocate/main/main.go
  src/disk_speed_check/disk_speed_check.go
  src/disk_speed_check/main/main.go
  src/domain_resolution/domain_resolution.go
  src/domain_resolution/domain_resolution_test.go
  src/domain_resolution/main/main.go
  src/free_addresses/main/main.go
  src/inventory/bmc.go
  src/inventory/disks.go
  src/inventory/inventory.go
  src/inventory/main/main.go
  src/inventory/memory.go
  src/inventory/memory_test.go
  src/inventory/system_vendor.go
  src/logs_sender/main/main.go
  src/logs_sender/send_logs.go
  src/next_step_runner/main/main.go
  src/ntp_synchronizer/main/main.go
  src/util/dry_reboot.go
  src/util/execute.go
  src/util/logging.go
  src/util/logging_test.go
  subsystem/agent_test.go
  subsystem/container_image_availability_test.go
  subsystem/utils.go
Labels: approved, lgtm, size/XL

#252 NO-ISSUE: Logs sender lsblk unknown column error fix
  src/logs_sender/send_logs.go
Labels: approved, lgtm, size/XS

#253 MGMT-8163 :Logs sender logs should be printed to stdout
  go.mod
  go.sum
  src/logs_sender/main/main.go
  src/util/logging.go
  src/util/logging_test.go
Labels: approved, lgtm, size/XL

#254 MGMT-7941: Fix agent dry reboot condition in wrong code path
  src/agent/main/main.go
Labels: approved, lgtm, size/S

#256 MGMT-7941: Allow forcing the IP address and hostname of the agent in dry mode
  src/commands/connectivity_check.go
  src/config/dry_run_config.go
  src/inventory/dry_inventory.go
  src/inventory/inventory.go
  src/util/dependencies.go
Labels: approved, lgtm, size/M

#257 MGMT-8294: Adapt assisted installer agent to latest swagger changes
  go.mod
  go.sum
  src/logs_sender/send_logs.go
Labels: approved, lgtm, size/L
