Repository openshift/assisted-installer-agent, pull requests merged in 2021-07, with the labels that each got.

#213 NO-ISSUE Fix linting errors on ocm-2.3 branch
  src/apivip_check/apivip_check.go
  src/commands/connectivity_check_test.go
  src/disk_speed_check/disk_speed_check_test.go
  src/inventory/boot_test.go
  src/inventory/interfaces.go
  src/inventory/interfaces_test.go
  src/util/network_interface.go
Labels: approved, lgtm

#215 MGMT-7210 Upgrade Go version to 1.16
  Dockerfile.assisted_installer_agent
  Dockerfile.assisted_installer_agent-build
  go.mod
Labels: approved, lgtm, size/XS

#218 MGMT-6977: Make sure that the image availability timeout is per tool invocation instead of timeout to pull single image.
  src/container_image_availability/container_image_availability.go
  src/container_image_availability/container_image_availability_test.go
Labels: approved, lgtm, size/M

#217 Bug 1980901: Parse GW nil as net zero
  src/inventory/interfaces.go
  src/inventory/routes.go
  src/inventory/routes_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/M

#219 MGMT-7383: Add v2 APIs to agent
  Makefile
  go.mod
  go.sum
  src/commands/register_node.go
  src/commands/service_api.go
  src/commands/step_processor.go
  src/config/agent_config.go
  src/config/connectivity_config.go
  subsystem/agent_test.go
  subsystem/apivip_check_test.go
  subsystem/container_image_availability_test.go
  subsystem/docker-compose.yml
  subsystem/lease_test.go
  subsystem/ntp_test.go
  subsystem/utils.go
Labels: approved, lgtm, size/L
