Repository openshift/assisted-installer-agent, pull requests merged in 2021-08, with the labels that each got.

#221 MGMT-7407: Remove V1 APIs from agent
  src/commands/register_node.go
  src/commands/service_api.go
  src/commands/step_processor.go
  src/config/agent_config.go
Labels: approved, lgtm, size/M

#220 Bug 1990060: Host returns no routes with multipart
  src/inventory/routes.go
  src/inventory/routes_test.go
Labels: approved, lgtm, size/M, bugzilla/valid-bug, bugzilla/severity-medium

#222 Bug 1994060: Change IP version to golang's unix constant
  src/inventory/routes.go
  src/inventory/routes_test.go
Labels: approved, lgtm, size/M, bugzilla/valid-bug, bugzilla/severity-medium

#224 MGMT-7443: add removable attr to Disk
  go.mod
  go.sum
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/L

#226 MGMT-7597: Remove ronniel1, and razregev from OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#228 MGMT-7659: Generate and update the agent
  Makefile
  src/dhcp_lease_allocate/mock_Dependencies.go
  src/inventory/interfaces_test.go
  src/inventory/mock_FileInfo.go
  src/inventory/mock_Interface.go
  src/scanners/mock_SerialDiscovery.go
  src/util/mock_IDependencies.go
Labels: approved, lgtm, size/L

#229 NO-ISSUE - Add eliorerz to OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#227 MGMT-5400: Get physical_bytes from ghw if dmidecode was failed
  go.sum
  src/inventory/memory.go
  src/inventory/memory_test.go
  src/util/dependencies.go
  src/util/mock_IDependencies.go
Labels: approved, lgtm, size/L
