Repository openshift/assisted-installer-agent, pull requests merged in 2021-09, with the labels that each got.

#225 OCPRHV-591: Add oVirt support to the agent side
  src/inventory/system_vendor.go
  src/inventory/system_vendor_test.go
Labels: approved, lgtm, ok-to-test, size/S

#232 MGMT-7457: Adding TPM version to host inventory.
  go.mod
  go.sum
  src/inventory/inventory.go
  src/inventory/tpm.go
  src/inventory/tpm_test.go
Labels: approved, lgtm, size/M

#236 MGMT-7847: Add a deprecation warning for the VerifyCidr option
  src/apivip_check/apivip_check.go
Labels: approved, lgtm, size/XS

#238 NO-ISSUE: Add flaper87 to approvers list
  OWNERS_ALIASES
Labels: size/XS

#237 MGMT-7761: Switch to stream8
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS

#234 NO-ISSUE: Add lranjbar to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
