Repository openshift/assisted-installer-agent, pull requests merged in 2022-04, with the labels that each got.

#320 MGMT-9807: Enable next step runner to run tools directly in addition to the running them in container
  src/commands/runner.go
  src/commands/step_processor.go
  src/next_step_runner/main/main.go
Labels: approved, lgtm, size/L

#322 MGMT-9806: Enable unifying agent and next step runner
  src/agent/agent.go
  src/agent/main/main.go
  src/commands/actions/next_step_runner.go
  src/commands/actions/next_step_runner_test.go
  src/commands/runner.go
  src/commands/step_processor.go
  src/next_step_runner/main/main.go
Labels: approved, lgtm, size/L

#324 NO-ISSUE: bump assisted-service version
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#325 [release-ocm-2.5] NO-ISSUE: bump assisted-service version
  go.mod
  go.sum
Labels: approved, lgtm, bugzilla/valid-bug, size/S

#327 [release-ocm-2.4] MGMT-9886: bump assisted-service version
  go.mod
  go.sum
Labels: approved, lgtm, bugzilla/valid-bug, size/S

#328 MGMT-9453: Implement params validation per each step
  go.mod
  go.sum
  src/agent/agent.go
  src/commands/actions/action.go
  src/commands/actions/api_vip_connectivity_check.go
  src/commands/actions/api_vip_connectivity_check_test.go
  src/commands/actions/connectivity_check_cmd.go
  src/commands/actions/connectivity_check_cmd_test.go
  src/commands/actions/dhcp_leases_cmd.go
  src/commands/actions/dhcp_leases_cmd_test.go
  src/commands/actions/disk_perfomance_check_cmd.go
  src/commands/actions/disk_perfomance_check_test.go
  src/commands/actions/domain_resolution_cmd.go
  src/commands/actions/domain_resolution_cmd_test.go
  src/commands/actions/free_addresses_cmd.go
  src/commands/actions/free_addresses_cmd_test.go
  src/commands/actions/image_availability_cmd.go
  src/commands/actions/image_availability_cmd_test.go
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  src/commands/actions/inventory_cmd.go
  src/commands/actions/inventory_cmd_test.go
  src/commands/actions/logs_gather.go
  src/commands/actions/logs_gather_test.go
  src/commands/actions/next_step_runner.go
  src/commands/actions/next_step_runner_test.go
  src/commands/actions/ntp_sync_cmd.go
  src/commands/actions/ntp_sync_cmd_test.go
  src/commands/actions/stop_installation.go
  src/commands/actions/stop_installation_test.go
  src/commands/runner.go
  src/connectivity_check/connectivity_check.go
  src/connectivity_check/connectivity_check_test.go
  src/connectivity_check/main/main.go
Labels: approved, lgtm, size/XXL

#332 NO-ISSUE: Capitalize ValidateCommon to enable accessing it externally
  src/commands/actions/action.go
  src/commands/actions/api_vip_connectivity_check.go
  src/commands/actions/connectivity_check_cmd.go
  src/commands/actions/dhcp_leases_cmd.go
  src/commands/actions/disk_perfomance_check_cmd.go
  src/commands/actions/domain_resolution_cmd.go
  src/commands/actions/free_addresses_cmd.go
  src/commands/actions/image_availability_cmd.go
  src/commands/actions/install_cmd.go
  src/commands/actions/inventory_cmd.go
  src/commands/actions/logs_gather.go
  src/commands/actions/next_step_runner.go
  src/commands/actions/ntp_sync_cmd.go
  src/commands/actions/stop_installation.go
Labels: approved, lgtm, size/S

#333 NO-ISSUE: Add utility function that creates custom journaled logger with specific host id.
  src/util/logging.go
Labels: approved, lgtm, size/XS

#335 MGMT-10080: Agent subsystem crashes on panic when trying to register host with no DMI information
  subsystem/dmi/bios_date
  subsystem/dmi/bios_release
  subsystem/dmi/bios_vendor
  subsystem/dmi/bios_version
  subsystem/dmi/board_asset_tag
  subsystem/dmi/board_name
  subsystem/dmi/board_serial
  subsystem/dmi/board_vendor
  subsystem/dmi/board_version
  subsystem/dmi/chassis_asset_tag
  subsystem/dmi/chassis_serial
  subsystem/dmi/chassis_type
  subsystem/dmi/chassis_vendor
  subsystem/dmi/chassis_version
  subsystem/dmi/ec_firmware_release
  subsystem/dmi/modalias
  subsystem/dmi/power/autosuspend_delay_ms
  subsystem/dmi/power/control
  subsystem/dmi/power/runtime_active_time
  subsystem/dmi/power/runtime_status
  subsystem/dmi/power/runtime_suspended_time
  subsystem/dmi/product_family
  subsystem/dmi/product_name
  subsystem/dmi/product_serial
  subsystem/dmi/product_sku
  subsystem/dmi/product_uuid
  subsystem/dmi/product_version
  subsystem/dmi/sys_vendor
  subsystem/dmi/uevent
  subsystem/docker-compose.yml
Labels: approved, lgtm, size/M

#338 NO-ISSUE: Create reply cache per session instead of global one
  src/commands/reply_cache.go
  src/commands/step_processor.go
Labels: approved, lgtm, size/S

#342 NO-ISSUE: in ci pulling image can be too quick and we can't validate 2 running image availability commands
  subsystem/container_image_availability_test.go
Labels: approved, lgtm, size/S
