Repository openshift/assisted-installer-agent, pull requests merged in 2022-11, with the labels that each got.

#449 MGMT-8460: Automatically rename discovered hosts
  src/inventory/inventory.go
  src/inventory/inventory_test.go
  src/inventory/main_test.go
Labels: approved, lgtm, size/L

#442 MGMT-11551: Retry when service fails
  src/session/inventory_session.go
  src/session/inventory_session_test.go
Labels: approved, lgtm, size/M

#433 MGMT-11970: Ensure that we handle an IP conflict correctly.
  src/connectivity_check/connectivity_check.go
  src/connectivity_check/connectivity_check_test.go
Labels: approved, lgtm, size/L

#438 MGMT-11551: Retry when service fails
  go.mod
  src/commands/commands_suite_test.go
  src/commands/step_processor.go
  src/commands/step_processor_test.go
Labels: approved, lgtm, size/L

#456 MGMT-12711: Verify that L2 connectivity checks are received grouped by ip+mac instead of just mac
  src/connectivity_check/connectivity_check.go
  src/connectivity_check/connectivity_check_test.go
Labels: approved, lgtm, size/M

#452 OCPBUGSM-46219: OCPBUGSM-46220: Update golang version to 1.18.1.
  Dockerfile.assisted_installer_agent
  Dockerfile.assisted_installer_agent-build
  Makefile
  go.mod
  go.sum
  pkg/journalLogger/journal.go
  pkg/journalLogger/mock_IJournalWriter.go
  src/commands/actions/download_boot_artifacts_cmd.go
  src/connectivity_check/connectivity_check_test.go
  src/container_image_availability/container_image_availability.go
  src/container_image_availability/mock_ImageAvailabilityDependencies.go
  src/dhcp_lease_allocate/dhcp_lease_allocate.go
  src/dhcp_lease_allocate/mock_Dependencies.go
  src/disk_speed_check/dependencies.go
  src/disk_speed_check/mock_IDependencies.go
  src/domain_resolution/domain_resolution.go
  src/domain_resolution/mock_DomainResolutionDependencies.go
  src/free_addresses/free_addresses.go
  src/free_addresses/mock_Executer.go
  src/inventory/interfaces_test.go
  src/inventory/mock_FileInfo.go
  src/inventory/mocks.go
  src/logs_sender/mock_LogsSender.go
  src/logs_sender/send_logs.go
  src/ntp_synchronizer/mock_NtpSynchronizerDependencies.go
  src/ntp_synchronizer/ntp_synchronizer.go
  src/scanners/machine_uuid_scanner.go
  src/scanners/mock_SerialDiscovery.go
  src/session/inventory_session.go
  src/tang_connectivity_check/tang_connectivity_check.go
  src/upgrade_agent/mock_Dependencies.go
  src/upgrade_agent/upgrade_agent.go
  src/util/dependencies.go
  src/util/logging.go
  src/util/logging_test.go
  src/util/mock_IDependencies.go
  src/util/mock_Interface.go
  src/util/mock_Link.go
  src/util/mock_RouteFinder.go
  src/util/mocks.go
  src/util/network.go
  src/util/network_interface.go
  src/util/test_utils.go
  subsystem/agent_test.go
  subsystem/utils.go
Labels: approved, lgtm, size/XXL

#459 MGMT-12760: Don't panic when retrying after no response
  src/session/inventory_session.go
Labels: approved, lgtm, size/XS

#460 Remove validation on commit messages
  Makefile
  hack/check-commit-message.sh
  hack/check-commits.sh
Labels: approved, lgtm, size/M
