Repository openshift/assisted-installer-agent, pull requests merged in 2022-09, with the labels that each got.

#427 MGMT-11185: disk_speed_check: escape colons when calling fio
  src/disk_speed_check/disk_speed_check.go
Labels: approved, lgtm, size/XS

#428 NO-ISSUE: Add @vrutkovs to `OWNERS_ALIASES`
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#386 MGMT-10936: Cleanup agent code for commands that are not run as with podman run anymore
  Dockerfile.assisted_installer_agent
  Dockerfile.ocp
  Makefile
Labels: approved, lgtm, size/S

#434 MGMT-12030: Pinning golang.org/x/sys dependency due to golang incompatibility
  Dockerfile.assisted_installer_agent-build
Labels: approved, lgtm, size/XS, bugzilla/valid-bug

#435 MGMT-11991: Move the reverse lookup failure message to debug in NTP synchronizer
  src/ntp_synchronizer/ntp_synchronizer.go
Labels: approved, lgtm, size/XS

#436 Update approvers and reviewers lists
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#437 MGMT-12139: Add offset to FIO disk speed check
  src/disk_speed_check/disk_speed_check.go
  src/disk_speed_check/disk_speed_check_test.go
Labels: approved, lgtm, size/XS
