Repository openshift/assisted-installer-agent, pull requests merged in 2022-07, with the labels that each got.

#389 NO-ISSUE: Add @rccrdpccl as approver
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#388 MGMT-10973: Copy coredns & keepalived static pod manifests in day-2 connectivity-check ignition
  src/apivip_check/apivip_check.go
Labels: approved, lgtm, size/M

#396 AGENT-263: Remove ENTRYPOINT from OCP Dockerfile
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#393 MGMT-11037: Update models for the upgrade-agent feature
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/github.com/openshift/assisted-service/internal/common/test_configuration.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/os_image.go
  vendor/github.com/openshift/assisted-service/models/route.go
  vendor/github.com/openshift/assisted-service/models/step_type.go
  vendor/github.com/openshift/assisted-service/models/upgrade_agent_request.go
  vendor/github.com/openshift/assisted-service/models/upgrade_agent_response.go
  vendor/github.com/openshift/assisted-service/models/upgrade_agent_result.go
  vendor/github.com/openshift/assisted-service/pkg/auth/authz_utils.go
  vendor/github.com/openshift/assisted-service/pkg/auth/rhsso_authenticator.go
  vendor/github.com/openshift/assisted-service/pkg/ocm/utils.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#341 MGMT-7741: Add TANG server connectivity check
  go.mod
  go.sum
  src/commands/actions/action.go
  src/commands/actions/tang_connectivity_check.go
  src/commands/actions/tang_connectivity_check_test.go
  src/logs_sender/mock_LogsSender.go
  src/scanners/machine_uuid_scanner_test.go
  src/tang_connectivity_check/tang_connectivity_check.go
  src/tang_connectivity_check/tang_connectivity_check_test.go
  src/util/test_utils.go
  vendor/github.com/containers/image/v5/LICENSE
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/helpers.go
  vendor/github.com/containers/image/v5/docker/reference/normalize.go
  vendor/github.com/containers/image/v5/docker/reference/reference.go
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/containers/image/v5/docker/reference/regexp.go
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/github.com/openshift/assisted-service/internal/common/test_configuration.go
  vendor/github.com/openshift/assisted-service/internal/metrics/metricsManager.go
  vendor/github.com/openshift/assisted-service/internal/metrics/mock_metrics_manager_api.go
  vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
  vendor/github.com/openshift/assisted-service/models/host.go
  vendor/github.com/openshift/assisted-service/models/step_type.go
  vendor/github.com/openshift/assisted-service/models/tang_connectivity_request.go
  vendor/github.com/openshift/assisted-service/models/tang_connectivity_response.go
  vendor/github.com/openshift/assisted-service/pkg/tang/tang_server.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#398 MGMT-11012: Add route metric to inventory
  src/inventory/routes.go
  src/inventory/routes_test.go
  src/logs_sender/send_logs.go
Labels: approved, lgtm, size/S

#399 MGMT-11037: Send full image reference in `discovery_image_version`
  README.md
  go.mod
  go.sum
  src/commands/service_api.go
  src/config/agent_config.go
  src/config/connectivity_config.go
  subsystem/docker-compose.yml
  subsystem/jq.go
  subsystem/utils.go
  vendor/github.com/itchyny/gojq/.dockerignore
  vendor/github.com/itchyny/gojq/.gitattributes
  vendor/github.com/itchyny/gojq/.gitignore
  vendor/github.com/itchyny/gojq/CHANGELOG.md
  vendor/github.com/itchyny/gojq/Dockerfile
  vendor/github.com/itchyny/gojq/LICENSE
  vendor/github.com/itchyny/gojq/Makefile
  vendor/github.com/itchyny/gojq/README.md
  vendor/github.com/itchyny/gojq/_gojq
  vendor/github.com/itchyny/gojq/builtin.go
  vendor/github.com/itchyny/gojq/builtin.jq
  vendor/github.com/itchyny/gojq/code.go
  vendor/github.com/itchyny/gojq/compare.go
  vendor/github.com/itchyny/gojq/compiler.go
  vendor/github.com/itchyny/gojq/debug.go
  vendor/github.com/itchyny/gojq/encoder.go
  vendor/github.com/itchyny/gojq/env.go
  vendor/github.com/itchyny/gojq/error.go
  vendor/github.com/itchyny/gojq/execute.go
  vendor/github.com/itchyny/gojq/func.go
  vendor/github.com/itchyny/gojq/go.dev.mod
  vendor/github.com/itchyny/gojq/go.dev.sum
  vendor/github.com/itchyny/gojq/gojq.go
  vendor/github.com/itchyny/gojq/iter.go
  vendor/github.com/itchyny/gojq/lexer.go
  vendor/github.com/itchyny/gojq/math.go
  vendor/github.com/itchyny/gojq/module_loader.go
  vendor/github.com/itchyny/gojq/normalize.go
  vendor/github.com/itchyny/gojq/operator.go
  vendor/github.com/itchyny/gojq/option.go
  vendor/github.com/itchyny/gojq/parser.go
  vendor/github.com/itchyny/gojq/parser.go.y
  vendor/github.com/itchyny/gojq/preview.go
  vendor/github.com/itchyny/gojq/query.go
  vendor/github.com/itchyny/gojq/release.go
  vendor/github.com/itchyny/gojq/scope_stack.go
  vendor/github.com/itchyny/gojq/stack.go
  vendor/github.com/itchyny/gojq/term_type.go
  vendor/github.com/itchyny/gojq/type.go
  vendor/github.com/itchyny/timefmt-go/CHANGELOG.md
  vendor/github.com/itchyny/timefmt-go/LICENSE
  vendor/github.com/itchyny/timefmt-go/Makefile
  vendor/github.com/itchyny/timefmt-go/README.md
  vendor/github.com/itchyny/timefmt-go/format.go
  vendor/github.com/itchyny/timefmt-go/parse.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#403 MGMT-10973: Filtered ignition should keep non-heavy elements
  src/apivip_check/apivip_check.go
Labels: approved, lgtm, size/XS

#400 MGMT-11037: Add upgrade-agent step
  src/commands/actions/action.go
  src/commands/actions/upgrade_agent_cmd.go
  src/commands/actions/upgrade_agent_cmd_test.go
  src/commands/step_processor.go
  src/next_step_runner/main/main.go
  src/upgrade_agent/mock_Dependencies.go
  src/upgrade_agent/upgrade_agent.go
  src/upgrade_agent/upgrade_agent_test.go
Labels: approved, lgtm, size/L

#406 NO-ISSUE: Add `jhernand` to `OWNERS_ALIASES`
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#407 MGMT-11262: Include `/etc/kubernetes/kubeconfig` in day-2 ignition
  src/apivip_check/apivip_check.go
Labels: approved, lgtm, size/XS

#408 MGMT-11300: cluster installation failed - host got disconnected cause agent failed to reach the service twice
  go.mod
  go.sum
  src/session/inventory_session.go
  src/session/inventory_session_test.go
  vendor/github.com/PuerkitoBio/rehttp/.travis.yml
  vendor/github.com/PuerkitoBio/rehttp/LICENSE
  vendor/github.com/PuerkitoBio/rehttp/README.md
  vendor/github.com/PuerkitoBio/rehttp/context_post17.go
  vendor/github.com/PuerkitoBio/rehttp/context_pre17.go
  vendor/github.com/PuerkitoBio/rehttp/rehttp.go
  vendor/github.com/go-ole/go-ole/com.go
  vendor/github.com/go-ole/go-ole/idispatch_windows.go
  vendor/github.com/go-ole/go-ole/ole.go
  vendor/github.com/go-ole/go-ole/safearray_windows.go
  vendor/github.com/go-ole/go-ole/safearrayconversion.go
  vendor/github.com/go-ole/go-ole/variables.go
  vendor/github.com/go-ole/go-ole/variant_arm.go
  vendor/github.com/go-ole/go-ole/variant_arm64.go
  vendor/github.com/go-ole/go-ole/variant_date_arm.go
  vendor/github.com/go-ole/go-ole/variant_date_arm64.go
  vendor/github.com/onsi/gomega/ghttp/handlers.go
  vendor/github.com/onsi/gomega/ghttp/test_server.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#412 MGMT-11356: Add option to log to stdout
  src/agent/main/main.go
  src/apivip_check/main/main.go
  src/config/agent_config.go
  src/config/subprocess_config.go
  src/connectivity_check/main/main.go
  src/container_image_availability/main/main.go
  src/dhcp_lease_allocate/main/main.go
  src/disk_speed_check/main/main.go
  src/domain_resolution/main/main.go
  src/free_addresses/main/main.go
  src/inventory/main/main.go
  src/logs_sender/main/main.go
  src/next_step_runner/main/main.go
  src/ntp_synchronizer/main/main.go
  src/util/logging.go
Labels: approved, lgtm, size/M

#414 NO-ISSUE: Fix type on convertStringArrayToInterfaceArray
  src/container_image_availability/container_image_availability_test.go
Labels: approved, lgtm, size/S
