Repository openshift/assisted-installer-agent, pull requests merged in 2022-03, with the labels that each got.

#297 MGMT-9344: Return non-zero exit when subsystem test fails
  Makefile
Labels: approved, lgtm, size/S

#298 MGMT-9481 Support linode serial/uuid
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
Labels: approved, lgtm, size/XS

#301 NO-ISSUE: Don't delete the subsystem_agent docker-compose image every time
  Makefile
Labels: approved, lgtm, size/XS

#302 NO-ISSUE: Bump go-openapi/runtime to 0.23.2
  go.mod
  go.sum
  src/session/inventory_session.go
Labels: approved, lgtm, size/M

#305 NO-ISSUE: add ci operator file
  .ci-operator.yaml
Labels: approved, lgtm, size/XS

#306 NO-ISSUE: replace .ci-operator.yaml to use local dockerfile
  .ci-operator.yaml
Labels: approved, lgtm, size/XS

#307 NO-ISSUE: remove .ci-operator.yaml file
  .ci-operator.yaml
Labels: approved, lgtm, size/XS

#308 NO-ISSUE update container golang version to 1.17
  Dockerfile.assisted_installer_agent
  Dockerfile.assisted_installer_agent-build
Labels: approved, lgtm, size/XS

#304 MGMT-9358 update assisted-service after split to submodules
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#311 MGMT-9344: Delete Jenkinsfile
  Jenkinsfile
Labels: approved, lgtm, size/M

#315 MGMT-9451: Moving to new service-agent protocol
  go.mod
  go.sum
  src/agent/main/main.go
  src/commands/actions/action.go
  src/commands/actions/api_vip_connectivity_check.go
  src/commands/actions/api_vip_connectivity_check_test.go
  src/commands/actions/connectivity_check_cmd.go
  src/commands/actions/connectivity_check_cmd_test.go
  src/commands/actions/dhcp_leases_cmd.go
  src/commands/actions/dhcp_leases_cmd_test.go
  src/commands/actions/disk_perfomance_check_cmd.go
  src/commands/actions/disk_perfomance_check_test.go
  src/commands/actions/domain_resolution_cmd.go
  src/commands/actions/domain_resolution_cmd_test.go
  src/commands/actions/free_addresses_cmd.go
  src/commands/actions/free_addresses_cmd_test.go
  src/commands/actions/image_availability_cmd.go
  src/commands/actions/image_availability_cmd_test.go
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  src/commands/actions/inventory_cmd.go
  src/commands/actions/inventory_cmd_test.go
  src/commands/actions/logs_gather.go
  src/commands/actions/logs_gather_test.go
  src/commands/actions/next_step_runner.go
  src/commands/actions/next_step_runner_test.go
  src/commands/actions/ntp_sync_cmd.go
  src/commands/actions/ntp_sync_cmd_test.go
  src/commands/actions/stop_installation.go
  src/commands/actions/stop_installation_test.go
  src/commands/service_api.go
  src/commands/start_agent.go
  src/commands/step_processor.go
  src/config/agent_config.go
  src/config/connectivity_config.go
Labels: approved, lgtm, size/XL

#316 MGMT-9451: Latest api fixes and moving to master branch of service models
  go.mod
  go.sum
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  src/commands/actions/logs_gather.go
  src/commands/actions/logs_gather_test.go
  src/commands/actions/next_step_runner.go
  src/commands/actions/next_step_runner_test.go
Labels: approved, lgtm, size/L

#321 NO-ISSUE: Pass agent image name to subsystem docker file
  Makefile
  subsystem/Dockerfile.agent_test
  subsystem/agent_test.go
Labels: approved, lgtm, size/S
