Repository openshift/assisted-installer-agent, pull requests merged in 2022-05, with the labels that each got.

#344 MGMT-10154: Remove usage of command on step object
  src/agent/agent.go
  src/commands/runner.go
  src/commands/step_processor.go
  subsystem/utils.go
Labels: approved, lgtm, size/S

#347 Bug 2081282: Implementing new service-agent protocol on agent side - backport of MGMT-7530
  go.mod
  go.sum
  src/agent/main/main.go
  src/commands/actions/action.go
  src/commands/actions/api_vip_connectivity_check.go
  src/commands/actions/api_vip_connectivity_check_test.go
  src/commands/actions/connectivity_check_cmd.go
  src/commands/actions/connectivity_check_cmd_test.go
  src/commands/actions/dhcp_leases_cmd.go
  src/commands/actions/dhcp_leases_cmd_test.go
  src/commands/actions/disk_perfomance_check_cmd.go
  src/commands/actions/disk_perfomance_check_test.go
  src/commands/actions/domain_resolution_cmd.go
  src/commands/actions/domain_resolution_cmd_test.go
  src/commands/actions/free_addresses_cmd.go
  src/commands/actions/free_addresses_cmd_test.go
  src/commands/actions/image_availability_cmd.go
  src/commands/actions/image_availability_cmd_test.go
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  src/commands/actions/inventory_cmd.go
  src/commands/actions/inventory_cmd_test.go
  src/commands/actions/logs_gather.go
  src/commands/actions/logs_gather_test.go
  src/commands/actions/next_step_runner.go
  src/commands/actions/next_step_runner_test.go
  src/commands/actions/ntp_sync_cmd.go
  src/commands/actions/ntp_sync_cmd_test.go
  src/commands/actions/stop_installation.go
  src/commands/actions/stop_installation_test.go
  src/commands/service_api.go
  src/commands/start_agent.go
  src/commands/step_processor.go
  src/config/agent_config.go
  src/config/connectivity_config.go
Labels: approved, lgtm, bugzilla/severity-unspecified, bugzilla/valid-bug, size/XXL

#348 AGENT-153: Add .ci-operator.yaml for OCP payload image
  .ci-operator.yaml
Labels: approved, lgtm, size/XS

#350 MGMT-9379: Validation should allow HA mode to be empty in parameters.
  go.mod
  go.sum
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/github.com/openshift/assisted-service/pkg/auth/rhsso_authz_handler.go
  vendor/github.com/openshift/assisted-service/pkg/ocm/accounts_mgmt.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/gorm.io/gorm/callbacks/helper.go
  vendor/gorm.io/gorm/finisher_api.go
  vendor/gorm.io/gorm/migrator/migrator.go
  vendor/gorm.io/gorm/scan.go
  vendor/gorm.io/gorm/schema/field.go
  vendor/gorm.io/gorm/schema/index.go
  vendor/gorm.io/gorm/schema/pool.go
  vendor/gorm.io/gorm/schema/serializer.go
  vendor/gorm.io/gorm/statement.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#352 NO-ISSUE: remove redundant ok-to-test label
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#357 MGMT-10454: Run next-step-runner with unlimited pids limit
  src/commands/actions/next_step_runner.go
Labels: approved, lgtm, size/XS

#359 MGMT-10514: additional NTP source failed to sync
  src/commands/actions/next_step_runner.go
  src/commands/actions/next_step_runner_test.go
Labels: approved, lgtm, size/XS

#362 MGMT-10003: If skip-installation-disk-cleanup is set path it to installer command
  go.mod
  go.sum
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  src/commands/step_processor.go
  vendor/github.com/openshift/assisted-service/models/host.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/github.com/openshift/assisted-service/models/interface.go
  vendor/github.com/openshift/assisted-service/models/step.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
