Repository openshift/assisted-installer-agent, pull requests merged in 2022-06, with the labels that each got.

#364 MGMT-9505: SMART data should include only errors
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/XS

#360 MGMT-9175: Pass all interfaces to the service
  src/inventory/interfaces.go
  src/inventory/interfaces_test.go
  src/scanners/machine_uuid_scanner_test.go
  src/util/mock.go
  src/util/mock_Interface.go
  src/util/mocks.go
  src/util/network_interface.go
Labels: approved, lgtm, size/L

#340 MGMT-9561: VSphere platform lacking setting disk.EnableUUID guidance
  Dockerfile.assisted_installer_agent
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/M

#366 Revert "MGMT-9175: Pass all interfaces to the service"
  src/inventory/interfaces.go
  src/inventory/interfaces_test.go
  src/scanners/machine_uuid_scanner_test.go
  src/util/mock.go
  src/util/mock_Interface.go
  src/util/mocks.go
  src/util/network_interface.go
Labels: approved, lgtm, size/L

#373 NO-ISSUE: fix smartmontools installation in U/S image
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, bugzilla/valid-bug

#372 ART-4057: Work around parsing issue on ART's tooling
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#371 MGMT-9175: Pass all interfaces to the service
  src/commands/actions/inventory_cmd.go
  src/inventory/interfaces.go
  src/inventory/interfaces_test.go
  src/inventory/inventory.go
  src/inventory/main/main.go
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
  src/util/mock.go
  src/util/mock_Interface.go
  src/util/mocks.go
  src/util/network_interface.go
Labels: approved, lgtm, size/L

#370 MGMT-10705: Return multipath device types
  go.mod
  go.sum
  src/inventory/disks.go
  src/inventory/disks_test.go
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/hvsock.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go
  vendor/github.com/cenkalti/backoff/v4/exponential.go
  vendor/github.com/containerd/continuity/AUTHORS
  vendor/github.com/go-openapi/validate/default_validator.go
  vendor/github.com/go-openapi/validate/example_validator.go
  vendor/github.com/go-openapi/validate/helpers.go
  vendor/github.com/go-openapi/validate/spec.go
  vendor/github.com/openshift/assisted-service/models/disk.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/github.com/ory/dockertest/v3/.gitignore
  vendor/github.com/ory/dockertest/v3/docker/auth.go
  vendor/github.com/ory/dockertest/v3/docker/image.go
  vendor/github.com/ory/dockertest/v3/dockertest.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#374 ART-4057: Only install `dmidecode` on x86_64 and aarch64
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#375 MGMT-10748: Use DriveType definitions from swagger
  go.mod
  go.sum
  src/inventory/disks.go
  src/inventory/disks_test.go
  vendor/github.com/openshift/assisted-service/internal/common/test_configuration.go
  vendor/github.com/openshift/assisted-service/internal/metrics/metricsManager.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/disk.go
  vendor/github.com/openshift/assisted-service/models/drive_type.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#376 Revert "MGMT-9175: Pass all interfaces to the service"
  src/commands/actions/inventory_cmd.go
  src/inventory/interfaces.go
  src/inventory/interfaces_test.go
  src/inventory/inventory.go
  src/inventory/main/main.go
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
  src/util/mock.go
  src/util/mock_Interface.go
  src/util/mocks.go
  src/util/network_interface.go
Labels: approved, lgtm, size/L

#363 NO-ISSUE: update bluemonday/runc/ignition pkgs
  go.mod
  go.sum
Labels: approved, lgtm, size/M, bugzilla/valid-bug

#379 NO-ISSUE: Add paul-maidment to approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#377 MGMT-9175: Pass all interfaces to the service
  src/inventory/interfaces.go
  src/inventory/interfaces_test.go
  src/scanners/machine_uuid_scanner_test.go
  src/util/mock.go
  src/util/mock_Interface.go
  src/util/mocks.go
  src/util/network_interface.go
Labels: approved, lgtm, size/L

#380 NO_ISSUE: fix mock generation.
  src/inventory/interfaces_test.go
  src/scanners/machine_uuid_scanner_test.go
  src/util/mocks.go
  src/util/test_utils.go
Labels: approved, lgtm, size/M

#378 AGENT-75: Add assisted installer images into OCP playload for Agent Work
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#384 NO-ISSUE: fix typo in word 'prerelease'
  src/commands/actions/install_cmd_test.go
Labels: approved, lgtm, size/XS
