Repository openshift/assisted-installer-agent, pull requests merged in 2022-08, with the labels that each got.

#416 MGMT-11527: fix flaky golangci-lint installation
  Dockerfile.assisted_installer_agent-build
Labels: approved, lgtm, size/XS

#419 MGMT-11575: Ignore empty MAC address for host UUID generation
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
Labels: approved, lgtm, size/M

#423 Bug 2119308: save-partlabel and save-partindex coreos-installer args…
  go.mod
  go.sum
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  src/commands/connectivity_check.go
  src/commands/connectivity_check_test.go
  src/commands/step_processor.go
Labels: approved, lgtm, bugzilla/severity-unspecified, size/L, bugzilla/valid-bug

#425 MGMT-10738: Include secure transport for downloading boot artifacts
  src/commands/actions/download_boot_artifacts_cmd.go
Labels: approved, lgtm, size/M

#422 MGMT-11447: Agent should report error when trying to pull ignition
  src/apivip_check/apivip_check.go
  src/apivip_check/apivip_check_test.go
Labels: approved, lgtm, size/L
