Repository openshift/assisted-installer-agent, pull requests merged in 2022-01, with the labels that each got.

#265 MGMT-8847: Add bf serial value to unknown serials in agent
  go.sum
  src/apivip_check/apivip_check.go
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
Labels: approved, lgtm, size/M

#266 NO-ISSUE: update assisted-service package
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#272 MGMT-8481: Allow fallback for generate uuid from mac for kaloom deployment
  src/commands/service_api.go
  src/inventory/interfaces_test.go
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
  src/util/mocks.go
Labels: approved, lgtm, size/L

#275 NO-ISSUE: fix dependabot commit messages to include NO-ISSUE
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#276 NO-ISSUE: remove redundant GitHub Actions files
  .github/workflows/build.yml
  .github/workflows/image-push.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/L

#277 MGMT-9040: include only Luks section of ignition in response
  go.mod
  go.sum
  src/apivip_check/apivip_check.go
  src/apivip_check/apivip_check_test.go
Labels: approved, lgtm, size/L

#278 MGMT-8752: handle ocp router 503 errors
  go.mod
  src/commands/errors.go
  src/commands/register_node.go
  src/commands/step_processor.go
  src/session/inventory_session.go
Labels: approved, lgtm, size/L
