Repository openshift/assisted-installer-agent, pull requests merged in 2022-10, with the labels that each got.

#441 MGMT-12139: Revert disk_speed_check related changes
  src/disk_speed_check/disk_speed_check.go
  src/disk_speed_check/disk_speed_check_test.go
Labels: approved, lgtm, size/S

#439 MGMT-8329: Disks with mounted parititions are ineligible
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/M

#288 NO-ISSUE: Dockerfile: don't install docs and weak dependencies
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS

#446 MGMT-12305: Fix a vulnerability which could cause a denial of service on version v0.3.7 of golang.org/x/text/language
  go.mod
  go.sum
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/secure/precis/profile.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/text/width/tables10.0.0.go
  vendor/golang.org/x/text/width/tables11.0.0.go
  vendor/golang.org/x/text/width/tables12.0.0.go
  vendor/golang.org/x/text/width/tables13.0.0.go
  vendor/golang.org/x/text/width/tables9.0.0.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
