Repository openshift/assisted-installer-agent, pull requests merged in 2022-12, with the labels that each got.

#461 OCPBUGS-3157: The connectivity check fails if an interface has a link-local address
  src/inventory/interfaces.go
  src/inventory/interfaces_test.go
Labels: approved, lgtm, size/S

#463 MGMT-12793: Tang unit tests should not query external URLs
  src/commands/actions/tang_connectivity_check.go
  src/tang_connectivity_check/tang_connectivity_check.go
  src/tang_connectivity_check/tang_connectivity_check_test.go
Labels: approved, lgtm, size/M

#462 NO-ISSUE: Stop retry when backoff expires or context is cancelled
  src/commands/step_processor.go
  src/commands/step_processor_test.go
Labels: approved, lgtm, size/XS

#451 MGMT-12537: detect virtualized environment
  src/commands/actions/inventory_cmd.go
  src/inventory/system_vendor.go
  src/inventory/system_vendor_test.go
Labels: approved, lgtm, size/M

#466 MGMT-12827: Don't try to rename when there is no usable NIC
  src/inventory/inventory.go
  src/inventory/inventory_test.go
Labels: approved, lgtm, size/S

#464 MGMT-12339: disk_speed_check: escape colons when calling fio (#427)
  src/disk_speed_check/disk_speed_check.go
Labels: approved, lgtm, size/XS
