Repository openshift/assisted-installer-agent, pull requests merged in 2022-02, with the labels that each got.

#282 MGMT-7813 Reduce smartcl verbosity
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/XS

#287 Install smartmontools from stream8 repos
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/S

#283 MGMT-9043: Set multipath device as eligible
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/L

#293 NO-ISSUE: remove Jenkins publishing step
  Jenkinsfile
  Makefile
Labels: approved, lgtm, size/S

#294 MGMT-9396: Fix UUID fallback
  src/apivip_check/apivip_check_test.go
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
Labels: approved, lgtm, size/M
