Repository openshift/assisted-installer-agent, pull requests merged in 2023-10, with the labels that each got.

#607 [release-ocm-2.8] OCPBUGS-14848: Filter out hidden devices (#558)
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/S, jira/invalid-bug, jira/severity-important, jira/valid-reference

#611 NO-ISSUE: add adriengentil as approver
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, jira/valid-reference

#614 MGMT-15900: Add enable-skip-mco-reboot flag to assisted installer install command
  go.mod
  go.sum
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  vendor/github.com/openshift/assisted-service/client/manifests/v2_list_cluster_manifests_parameters.go
  vendor/github.com/openshift/assisted-service/internal/gencrypto/token.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/github.com/openshift/assisted-service/pkg/validations/validations.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/github.com/openshift/assisted-service/restapi/operations/manifests/v2_list_cluster_manifests_parameters.go
  vendor/github.com/openshift/assisted-service/restapi/operations/manifests/v2_list_cluster_manifests_urlbuilder.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, jira/valid-reference

#617 Shrink agent image
  Dockerfile.assisted_installer_agent
  Dockerfile.ocp
  Makefile
  src/agent/main/main.go
  src/disk_speed_check/main.go
  src/free_addresses/main.go
  src/inventory/main.go
  src/logs_sender/main.go
  src/next_step_runner/main.go
Labels: approved, lgtm, size/L

#619 MGMT-16039: upgrade to golang 1.20
  Dockerfile.assisted_installer_agent
  Dockerfile.assisted_installer_agent-build
  go.mod
  src/apivip_check/apivip_check_test.go
Labels: approved, lgtm, size/S, jira/valid-reference
