Repository openshift/assisted-installer-agent, pull requests merged in 2023-08, with the labels that each got.

#584 MGMT-15359: support appliance multipath virtual device
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#585 MGMT-14933: Detect if the host in running on OCI
  src/inventory/system_vendor.go
  src/inventory/system_vendor_test.go
  src/util/dependencies.go
  src/util/mock_IDependencies.go
Labels: approved, lgtm, size/M, jira/valid-reference

#586 OCPBUGS-17251: Bumping golang.org/x/net
  go.mod
  go.sum
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_loong64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/text/language/match.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, jira/valid-reference

#582 Revert "MGMT-15235: Compile with CGO_ENABLED=1 for FIPS"
  Makefile
Labels: approved, lgtm, size/XS, jira/valid-reference

#588 MGMT-15235: Compile with CGO_ENABLED=1 for amd64
  Makefile
Labels: approved, lgtm, size/XS, jira/valid-reference

#589 MGMT-15235: Allow setting CGO_ENABLED flag
  Makefile
Labels: approved, lgtm, size/XS, jira/valid-reference
