Repository openshift/assisted-installer-agent, pull requests merged in 2023-06, with the labels that each got.

#553 MGMT-13009: Auto rename host with VLAN
  src/inventory/inventory.go
  src/inventory/inventory_test.go
Labels: approved, lgtm, size/S, jira/valid-reference

#554 MGMT-14540: Mark Appliance disk(s) with a partition name prefix 'agent' as eligible
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/M, jira/valid-reference

#559 [release-4.13] OCPBUGS-14992: Filter out hidden devices
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/S, jira/severity-important, jira/valid-bug, jira/valid-reference
