Repository openshift/assisted-installer-agent, pull requests merged in 2023-01, with the labels that each got.

#471 MGMT-12906: Refactor connectivity check
  src/commands/actions/connectivity_check_cmd.go
  src/connectivity_check/connectivity_check.go
  src/connectivity_check/connectivity_check_test.go
  src/connectivity_check/connectivity_runner.go
  src/connectivity_check/connectivity_runner_test.go
  src/connectivity_check/dry_run_checkers.go
  src/connectivity_check/ipv4_arping_checker.go
  src/connectivity_check/ipv4_arping_checker_test.go
  src/connectivity_check/ipv6_nmap_checker.go
  src/connectivity_check/ipv6_nmap_checker_test.go
  src/connectivity_check/main/main.go
  src/connectivity_check/mock_Checker.go
  src/connectivity_check/mock_Executer.go
  src/connectivity_check/mock_ResultReporter.go
  src/connectivity_check/ping_checker.go
  src/connectivity_check/ping_checker_test.go
  src/connectivity_check/util.go
Labels: approved, lgtm, size/XXL

#480 OCPBUGS-5714: CVE-2021-4238 assisted-installer-agent-container: goutils
  go.sum
Labels: approved, lgtm, size/XS, bugzilla/valid-bug, jira/valid-bug

#484 MGMT-13420: Adding cleanup of next-step-runner before starting it.
  src/commands/actions/next_step_runner.go
Labels: approved, lgtm, size/S, jira/valid-reference

#483 MULTIARCH-3239 -- Add multipath FC disk check for Power
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/M
