Repository openshift/assisted-installer-agent, pull requests merged in 2023-07, with the labels that each got.

#565 [release-4.13] OCPBUGS-15557: vendor agent-installer-utils to 79b142
  go.mod
  go.sum
  vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/app.go
  vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/checks/engine.go
  vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/controller.go
  vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/ui.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, jira/severity-important, jira/valid-bug, jira/valid-reference

#569 MGMT-15235: Compile with CGO_ENABLED=1 for FIPS
  Makefile
Labels: approved, lgtm, size/XS, jira/valid-reference

#571 [release-ocm-2.6] MGMT-15235: Compile with CGO_ENABLED=1 for FIPS
  Makefile
Labels: approved, lgtm, size/XS, jira/valid-reference

#576 OCPBUGS-16373: Ignore arping errors on RHEL 9
  src/connectivity_check/ipv4_arping_checker.go
Labels: approved, lgtm, size/XS, jira/valid-bug, jira/severity-critical, jira/valid-reference

#579 MGMT-15343: dependabot group updates
  .github/dependabot.yml
Labels: approved, lgtm, size/S, jira/valid-reference

#581 MGMT-15343: dependabot remove docker
  .github/dependabot.yml
Labels: approved, lgtm, size/S, jira/valid-reference

#583 MGMT-13111: Freeze on `404 Not Found`
  src/commands/step_processor.go
Labels: approved, lgtm, size/XS, jira/valid-reference
