Repository openshift/assisted-installer-agent, pull requests merged in 2023-02, with the labels that each got.

#487 Fix the upstream dockerfile build on non-x86 platform
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS

#489 Remove S.M.A.R.T. collection
  Dockerfile.assisted_installer_agent
  Dockerfile.ocp
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/M

#492 MGMT-13665: Bring full journal by default in log gather
  src/config/logs_sender_config.go
  src/logs_sender/send_logs.go
  src/logs_sender/send_logs_test.go
Labels: approved, lgtm, size/S, jira/valid-reference

#498 Make the agent team be the OWNERS of the Dockerfile.ocp file
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#500 [release-4.12] OCPBUGS-7889: Add sg3_utils package
  Dockerfile.ocp
Labels: approved, lgtm, size/XS, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#501 MGMT-13758: In connectivity check, ARPING checks should not run on nics without valid IPv4 address
  src/connectivity_check/connectivity_check_test.go
  src/connectivity_check/connectivity_runner.go
  src/connectivity_check/connectivity_runner_test.go
  src/connectivity_check/dry_run_checkers.go
  src/connectivity_check/ipv4_arping_checker.go
  src/connectivity_check/ipv4_arping_checker_test.go
  src/connectivity_check/ipv6_nmap_checker.go
  src/connectivity_check/ipv6_nmap_checker_test.go
  src/connectivity_check/util.go
  src/connectivity_check/util_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#505 vendor agent-installer-utils
  go.mod
  go.sum
  vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/app.go
  vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/checks/engine.go
  vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/check_page.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
