Repository openshift/assisted-installer-agent, pull requests merged in 2024-02, with the labels that each got.

#657 [release-ocm-2.9] MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842 (#656)
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#664 MGMT-16459: [STG] Cluster 4.15.0-rc.0 with HTTP Proxy failed on timeout due the failed to StartContainer for etcd with CrashLoopBackOff
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#666 [release-ocm-2.10] MGMT-16878: Set restricted list of approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, jira/valid-reference
