Repository openshift/assisted-installer-agent, pull requests merged in 2024-10, with the labels that each got.

#787 MGMT-18923: Refactor getGPUs
  README.md
  src/config/subprocess_config.go
  src/inventory/gpu.go
  src/inventory/gpu_test.go
  src/inventory/inventory.go
  src/util/dependencies.go
  src/util/mock_IDependencies.go
  src/util/mock_Interface.go
  src/util/mock_Link.go
  src/util/mock_RouteFinder.go
Labels: approved, lgtm, size/XL, jira/valid-reference

#783 OCPBUGS-42157: Switch to github.com/docker/distribution/reference to Mitigate CVE-2024-3727
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#795 [release-ocm-2.12] MGMT-18932: Reduce the owners list
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, jira/valid-reference

#796 MGMT-18923: Add hwdata package to inventory dependencies
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#800 NO-ISSUE: Add additional test for GPU cards with multiple PCI functions
  src/inventory/gpu_test.go
Labels: approved, lgtm, size/M, jira/valid-reference

#806 NO-ISSUE: Pin gocov version
  Dockerfile.assisted_installer_agent-build
Labels: approved, lgtm, size/XS, jira/valid-reference

#799 OCPBUGS-43006: Fix bash string comparison during image build
  Dockerfile.ocp
Labels: approved, lgtm, size/XS, jira/valid-bug, jira/valid-reference

#817 ACM-15078: Fixing agents reuse problem in z/VM after reclaim
  src/commands/actions/download_boot_artifacts_cmd.go
  src/commands/actions/reboot_for_reclaim.go
  src/commands/actions/reboot_for_reclaim_test.go
Labels: approved, lgtm, size/M, jira/valid-reference
