Repository openshift/assisted-installer-agent, pull requests merged in 2024-09, with the labels that each got.

#761 MGMT-18837: Fix broken build due to base image change.
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#776 MGMT-17103: Fixing boot issue for IBMZ hosts in reclaim
  src/commands/actions/download_boot_artifacts_cmd.go
  src/commands/actions/reboot_for_reclaim.go
Labels: approved, lgtm, size/M, jira/valid-reference

#778 MGMT-18839: Retry downloading boot artifacts
  src/commands/actions/download_boot_artifacts_cmd.go
Labels: approved, lgtm, size/M, jira/valid-reference

#784 MGMT-18466: improve depndabot grouping
  .github/dependabot.yml
Labels: approved, lgtm, size/XS, jira/valid-reference

#790 [release-ocm-2.11] MGMT-18839: Retry downloading boot artifacts (#778)
  src/commands/actions/download_boot_artifacts_cmd.go
Labels: approved, lgtm, size/M, jira/valid-reference

#789 OCPBUGS-42331: Switch to github.com/docker/distribution/reference to mitigate CVE-2024-3727
  go.mod
  go.sum
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/github.com/openshift/assisted-service/models/disk.go
  vendor/github.com/openshift/assisted-service/pkg/auth/agent_local_authenticator.go
  vendor/github.com/openshift/assisted-service/pkg/auth/authenticator.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, jira/valid-bug, jira/valid-reference
