Repository openshift/assisted-installer-agent, pull requests merged in 2024-12, with the labels that each got.

#828 MGMT-19390: Update mce's tekton pipelines to be multi-arch
  .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-main-push.yaml
Labels: approved, lgtm, size/S, jira/valid-reference

#821 MGMT-19166: Implement MTU checker
  src/connectivity_check/connectivity_check.go
  src/connectivity_check/connectivity_runner.go
  src/connectivity_check/mtu_checker.go
  src/connectivity_check/mtu_checker_test.go
  src/connectivity_check/util.go
  src/connectivity_check/util_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#835 MGMT-19408: Create tekton pipelines for acm 2.13
  .tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml
Labels: approved, lgtm, size/XL, jira/valid-reference

#841 MGMT-19453: Add downstream dockerfile
  Dockerfile.assisted_installer_agent-downstream
Labels: approved, lgtm, size/M, jira/valid-reference

#851 MGMT-19507: Stop using multi-arch builds in konflux
  .tekton/assisted-installer-agent-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-downstream-main-push.yaml
  .tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-main-push.yaml
Labels: approved, lgtm, size/S, jira/valid-reference

#850 OCPBUGS-35716: expand unknown mb serials with "(none)"
  src/scanners/machine_uuid_scanner.go
  src/scanners/machine_uuid_scanner_test.go
Labels: approved, lgtm, size/XS, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#866 [release-ocm-2.12] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, jira/valid-reference

#863 [release-ocm-2.9] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, jira/valid-reference

#865 [release-ocm-2.11] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, jira/valid-reference

#864 [release-ocm-2.10] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, jira/valid-reference

#868 MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#872 [release-ocm-2.12] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#869 [release-ocm-2.9] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#871 [release-ocm-2.11] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#870 [release-ocm-2.10] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference
