Repository openshift/assisted-installer-agent, pull requests merged in 2024-07, with the labels that each got.

#735 NO-ISSUE: Migrate build image to use registry.access.redhat.com/ubi9/…
  Dockerfile.assisted_installer_agent-build
  Makefile
  subsystem/ntp_test.go
  subsystem/utils.go
Labels: approved, lgtm, size/S, jira/valid-reference

#746 [release-ocm-2.8] MGMT-18332: Use centos stream 9 as the base image for test container
  .golangci.yml
  Dockerfile.assisted_installer_agent-build
  Makefile
  subsystem/utils.go
Labels: approved, lgtm, size/M, jira/valid-reference

#747 [release-ocm-2.9] MGMT-18332: Use centos stream 9 as the base image for test container
  .golangci.yml
  Dockerfile.assisted_installer_agent-build
  Makefile
  subsystem/utils.go
Labels: approved, lgtm, size/M, jira/valid-reference

#748 [release-ocm-2.10] MGMT-18332: Use centos stream 9 as the base image for test container
  .golangci.yml
  Dockerfile.assisted_installer_agent-build
Labels: approved, lgtm, size/M, jira/valid-reference

#750 MGMT-18332: Use centos stream 9 as the base image for test container
  .golangci.yml
  Dockerfile.assisted_installer_agent-build
Labels: approved, lgtm, size/M, jira/valid-reference

#754 NO-ISSUE: fix for ARM and multi images
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#757 [release-ocm-2.10] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#755 [release-ocm-2.11] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#758 [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted_installer_agent
  Dockerfile.assisted_installer_agent-build
  subsystem/Dockerfile.agent_test
  subsystem/lease_test.go
Labels: approved, lgtm, size/M, jira/valid-reference

#759 [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  Dockerfile.assisted_installer_agent
  Dockerfile.assisted_installer_agent-build
  subsystem/Dockerfile.agent_test
  subsystem/lease_test.go
Labels: approved, lgtm, size/M, jira/valid-reference
