Repository openshift/assisted-installer-agent, pull requests merged in 2024-11, with the labels that each got.

#819 MGMT-18464: MGMT-18452: Add validations to make iSCSI disk eligible
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#823 NO-ISSUE: Add linoyaslan to approvers list
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, jira/valid-reference

#826 NO-ISSUE: Add giladravid16 and pastequo to approvers list
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, jira/valid-reference

#825 MGMT-19371: Add downstream dockerfile for mce
  Dockerfile.assisted_installer_agent-mce
Labels: approved, lgtm, size/M, jira/valid-reference
