Repository openshift/assisted-installer-agent, pull requests merged in 2024-06, with the labels that each got.

#721 [release-ocm-2.9] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#723 [release-ocm-2.8] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#724 [release-ocm-2.7] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#728 [release-ocm-2.11] MGMT-18187: Reduce the list of approvers for ocm-2.11
  OWNERS_ALIASES
Labels: approved, lgtm, size/S, jira/valid-reference

#733 MGMT-17867: fix multipath inventory to include wwn
  src/inventory/disks.go
  src/inventory/disks_test.go
Labels: approved, lgtm, size/M, jira/valid-reference
