Repository openshift/assisted-installer-agent, pull requests merged in 2024-08, with the labels that each got.

#727 MGMT-17560: Report iSCSI host IP address in inventory
  go.mod
  go.sum
  src/inventory/disks.go
  src/inventory/disks_test.go
  vendor/github.com/imdario/mergo/CONTRIBUTING.md
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/SECURITY.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/github.com/openshift/assisted-service/internal/common/test_configuration.go
  vendor/github.com/openshift/assisted-service/internal/constants/manifests.go
  vendor/github.com/openshift/assisted-service/models/disk.go
  vendor/github.com/openshift/assisted-service/models/iscsi.go
  vendor/github.com/openshift/assisted-service/models/manifest.go
  vendor/github.com/openshift/assisted-service/pkg/auth/agent_local_authenticator.go
  vendor/github.com/openshift/assisted-service/pkg/auth/authenticator.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_wasip1.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/aliases/aliases.go
  vendor/golang.org/x/tools/internal/aliases/aliases_go121.go
  vendor/golang.org/x/tools/internal/aliases/aliases_go122.go
  vendor/golang.org/x/tools/internal/event/tag/tag.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/internal/typesinternal/errorcode.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/schemaconv/smd.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, jira/valid-reference

#767 MGMT-18521: fix NTP sources are not valid
  subsystem/ntp_test.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#762 MGMT-18511: update golang 1.21
  Dockerfile.assisted_installer_agent
  Dockerfile.assisted_installer_agent-build
  go.mod
  go.sum
Labels: approved, lgtm, size/S, jira/valid-reference

#772 MGMT-18475: disabling CGO
  Makefile
Labels: approved, lgtm, size/XS, jira/valid-reference
