Repository openshift/assisted-installer-agent, pull requests merged in 2025-06, with the labels that each got.

#1010 [release-ocm-2.14] NO-ISSUE: Reduce owners list for release-2.14 branch
  OWNERS_ALIASES
Labels: approved, lgtm, ok-to-test, size/S, jira/valid-reference

#1009 NO-ISSUE: Modify Konflux YAMLs to ocm-2.15
  .tekton/assisted-installer-agent-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-2-15-push.yaml
Labels: approved, lgtm, ok-to-test, size/S, jira/valid-reference

#1015 NO-ISSUE: Test
  src/connectivity_check/mtu_checker_test.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#1020 run go mod tidy / vendor
  go.mod
  go.sum
Labels: size/S

#1016 Revert "NO-ISSUE: Test"
  src/connectivity_check/mtu_checker_test.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#1025 MGMT-20858: apply tags migration
  .tekton/assisted-installer-agent-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-2-13-push.yaml
Labels: approved, lgtm, size/M, jira/valid-reference

#1026 MGMT-20858: apply tags migration
  .tekton/assisted-installer-agent-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-agent-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-main-push.yaml
  .tekton/assisted-installer-agent-ds-main-pull-request.yaml
  .tekton/assisted-installer-agent-ds-main-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#1029 MGMT-20868: trust also system certs
  src/session/inventory_session.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#999 MGMT-20023: Route inventory deleted when route without next hop interface
  src/inventory/routes.go
  src/inventory/routes_test.go
Labels: approved, lgtm, size/XS, jira/valid-reference
