Repository openshift/assisted-installer-agent, pull requests merged in 2025-04, with the labels that each got.

#956 OCPBUGS-53712: Bump golang-jwt/jwt/v4 to 4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/severity-important, jira/valid-bug, jira/valid-reference

#963 OCPBUGS-53713: Bump golang-jwt/jwt/v4 to 4.5.2 in release-4.18
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, size/M, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#964 OCPBUGS-53711: Bump jwt to 4.5.2 in release-4.17
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, size/M, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#980 [release-ocm-2.12]-ACM-19170: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#981 [release-ocm-2.11]-ACM-19169: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#983 [release-ocm-2.9]-ACM-19167: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#971 OCPBUGS-53710: Bump jwt to 4.5.2 in release-4.16
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, size/M, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#979 [release-ocm-2.13]-ACM-19168: CVE-2025-30204 - Bump github.com/golang-jwt/jwt/v4 to version v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, jira/valid-reference

#988 NO-ISSUE: Apply konflux migration
  .tekton/assisted-installer-agent-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-2-14-push.yaml
  .tekton/assisted-installer-agent-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-main-push.yaml
  .tekton/assisted-installer-agent-ds-main-pull-request.yaml
  .tekton/assisted-installer-agent-ds-main-push.yaml
Labels: approved, lgtm, size/S, jira/valid-reference

#987 NO-ISSUE: apply konflux migration 2.13
  .tekton/assisted-installer-agent-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-2-13-push.yaml
  .tekton/assisted-installer-agent-acm-ds-main-pull-request.yaml
  .tekton/assisted-installer-agent-acm-ds-main-push.yaml
  .tekton/assisted-installer-agent-ds-main-pull-request.yaml
  .tekton/assisted-installer-agent-ds-main-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#972 OCPBUGS-53706: Bump jwt to 4.5.2 in release-4.15
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, size/M, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#973 OCPBUGS-53707: Bump golang-jwt/jwt/v4 to 4.5.2 in release-4.14
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#997 NO-ISSUE: Update assisted-service's version
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/internal/common/common.go
  vendor/github.com/openshift/assisted-service/internal/common/error_utils.go
  vendor/github.com/openshift/assisted-service/internal/constants/files.go
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_role.go
  vendor/github.com/openshift/assisted-service/models/host_role_update_params.go
  vendor/github.com/openshift/assisted-service/models/host_update_params.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  vendor/github.com/openshift/assisted-service/pkg/ocm/utils.go
  vendor/github.com/openshift/assisted-service/restapi/embedded_spec.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/list_cluster_hosts_parameters.go
  vendor/github.com/openshift/assisted-service/restapi/operations/installer/v2_download_cluster_files_parameters.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, jira/valid-reference
