Repository openshift/assisted-installer-agent, pull requests merged in 2025-02, with the labels that each got.

#904 NO-ISSUE: Increase image pull timeout during install
  src/commands/actions/install_cmd.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#909 NO-ISSUE: Remove unnecessary tekton tasks
  .tekton/assisted-installer-agent-ds-main-pull-request.yaml
  .tekton/assisted-installer-agent-ds-main-push.yaml
Labels: approved, lgtm, size/L, jira/valid-reference

#914 MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/S, jira/valid-reference

#917 [release-ocm-2.10] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#918 [release-ocm-2.9] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted_installer_agent
Labels: approved, lgtm, size/XS, jira/valid-reference

#920 MGMT-19588: Also use bond interface for hostname workaround
  src/inventory/inventory.go
  src/inventory/inventory_test.go
Labels: approved, lgtm, size/M, jira/valid-reference

#910 MGMT-19927: Modify MTU Check to Only MTUs != 1500
  src/connectivity_check/mtu_checker.go
  src/connectivity_check/mtu_checker_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#911 MGMT-19420: Replace HighAvailabilityMode with ControlPlaneCount
  go.mod
  go.sum
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, jira/valid-reference
