Repository openshift/assisted-installer-agent, pull requests merged in 2025-01, with the labels that each got.

#877 NO-ISSUE: OCPBUGS-43352 calculate outgoing interface for arping
  src/connectivity_check/connectivity_check_test.go
  src/connectivity_check/ipv4_arping_checker.go
  src/connectivity_check/ipv4_arping_checker_test.go
Labels: approved, lgtm, size/L, jira/valid-reference

#882 MGMT-19595: Push latest tag for downstream image after merge to konflux int repo
  .tekton/assisted-installer-agent-downstream-main-push.yaml
Labels: approved, lgtm, size/XS, jira/valid-reference

#883 MGMT-19381: Change downstream base images to rhel9.4 instead of ubi9
  Dockerfile.assisted_installer_agent-downstream
  Dockerfile.assisted_installer_agent-mce
Labels: approved, lgtm, size/XS, jira/valid-reference

#857 OCPBUGS-45910: Fix cpu clockspeed for s390x
  src/inventory/cpu.go
  src/inventory/cpu_test.go
Labels: approved, lgtm, size/M, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#889 MGMT-19645: Configure a few things for releasing in konflux
  .tekton/assisted-installer-agent-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-downstream-main-push.yaml
  .tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-main-push.yaml
  Dockerfile.assisted_installer_agent-downstream
  Dockerfile.assisted_installer_agent-mce
  rpm-prefetching/README.md
  rpm-prefetching/rpms.in.yaml
  rpm-prefetching/rpms.lock.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#892 NO-ISSUE: Make konflux builds for downstream images to be multi-arch
  .tekton/assisted-installer-agent-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-downstream-main-push.yaml
Labels: approved, lgtm, size/XS, jira/valid-reference

#893 NO-ISSUE: Stop removing stuff from the downstream image that are needed for preflight-check to succeed
  Dockerfile.assisted_installer_agent-downstream
Labels: approved, lgtm, size/S, jira/valid-reference

#896 MGMT-19734: Add renovate config to limit number of PRs
  renovate.json
Labels: approved, lgtm, size/XS, jira/valid-reference

#898 NO-ISSUE: Update buildah image to fix a bug with SBOM
  .tekton/assisted-installer-agent-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-downstream-main-push.yaml
  .tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml
  .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml
  .tekton/assisted-installer-agent-mce-downstream-main-push.yaml
Labels: approved, lgtm, size/S, jira/valid-reference

#897 MGMT-19100: Allow install to the existing root filesystem
  go.mod
  go.sum
  src/commands/actions/install_cmd.go
  src/commands/actions/install_cmd_test.go
  src/inventory/disks.go
  src/inventory/disks_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/client/operators/operators_client.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_parameters.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_responses.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_parameters.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_responses.go
  vendor/github.com/openshift/assisted-service/models/bundle.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  vendor/github.com/openshift/assisted-service/models/load_balancer.go
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, jira/valid-reference

#899 MGMT-19102: Add boot device info to inventory
  Dockerfile.assisted_installer_agent-build
  go.mod
  go.sum
  pkg/journalLogger/mock_IJournalWriter.go
  src/connectivity_check/mock_Checker.go
  src/connectivity_check/mock_Executer.go
  src/connectivity_check/mock_ResultReporter.go
  src/container_image_availability/mock_ImageAvailabilityDependencies.go
  src/dhcp_lease_allocate/mock_Dependencies.go
  src/disk_speed_check/mock_IDependencies.go
  src/domain_resolution/mock_DomainResolutionDependencies.go
  src/free_addresses/mock_Executer.go
  src/inventory/boot.go
  src/inventory/boot_test.go
  src/inventory/mock_FileInfo.go
  src/logs_sender/mock_LogsSender.go
  src/ntp_synchronizer/mock_NtpSynchronizerDependencies.go
  src/scanners/mock_SerialDiscovery.go
  src/upgrade_agent/mock_Dependencies.go
  src/util/dependencies.go
  src/util/mock_IDependencies.go
  src/util/mock_Interface.go
  src/util/mock_Link.go
  src/util/mock_RouteFinder.go
  src/vips_verifier/mock_Executer.go
  vendor/github.com/openshift/assisted-service/models/boot.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, jira/valid-reference
