Repository openshift/assisted-installer-agent, pull requests merged in 2025-07, with the labels that each got.

#1007 MGMT-20669: Fix hostname update for inventory get host
  src/commands/actions/next_step_runner.go
Labels: approved, lgtm, size/XS, ok-to-test, jira/valid-reference

#1028 MGMT-20141: collecting and uploading ironic-agent logs
  src/config/logs_sender_config.go
Labels: approved, lgtm, size/XS, jira/valid-reference

#1062 OCPBUGS-58845,OCPBUGS-58844: Bump glog to v1.2.5 in release-4.19
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1069 OCPBUGS-58660,OCPBUGS-58655: Bump glog to v1.2.5 in release-4.18
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
